//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidTable
    {
        public int bidID { get; set; }
        public Nullable<int> bidPrice { get; set; }
        public string userName { get; set; }
        public Nullable<int> productId { get; set; }
        public string productName { get; set; }
        public string bidStatus { get; set; }
    }
}
