//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class productTable
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public string productInfo { get; set; }
        public Nullable<int> basePrice { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> biddedPrice { get; set; }
        public string productCategory { get; set; }
        public string uploader { get; set; }
        public string bidder { get; set; }
        public byte[] image { get; set; }
    }
}
