//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string userStatus { get; set; }
        public string role { get; set; }
    }
}
