//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationScoutApp.QuakeServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuakeServiceRef.IQuakeService")]
    public interface IQuakeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuakeService/getQuakeIndex", ReplyAction="http://tempuri.org/IQuakeService/getQuakeIndexResponse")]
        decimal getQuakeIndex(decimal lat, decimal lon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuakeService/getQuakeIndex", ReplyAction="http://tempuri.org/IQuakeService/getQuakeIndexResponse")]
        System.Threading.Tasks.Task<decimal> getQuakeIndexAsync(decimal lat, decimal lon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuakeServiceChannel : LocationScoutApp.QuakeServiceRef.IQuakeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuakeServiceClient : System.ServiceModel.ClientBase<LocationScoutApp.QuakeServiceRef.IQuakeService>, LocationScoutApp.QuakeServiceRef.IQuakeService {
        
        public QuakeServiceClient() {
        }
        
        public QuakeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuakeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuakeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuakeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal getQuakeIndex(decimal lat, decimal lon) {
            return base.Channel.getQuakeIndex(lat, lon);
        }
        
        public System.Threading.Tasks.Task<decimal> getQuakeIndexAsync(decimal lat, decimal lon) {
            return base.Channel.getQuakeIndexAsync(lat, lon);
        }
    }
}
